spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/bikeshop_db
    username: postgres
    password: fss12296
  jpa:
    hibernate:
     ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true

java:
  runtime:
    version: correto11